### ISSUE TITLE
[1.21.1] [Sinytra Connector] Error when joining the server!

### ISSUE THREAD

**Issue by DynmaicNeo** [ZsoltMolnarrr/CombatSpells#80]
When i join the server of my minecraft it says Network configuration task not seupported: spell_engine:config 

and the console errror is :-
[06:51:17] [localSession-7-1/INFO]: DynamicNeo00 (logged in as: DynamicNeo00) has connected to the Java server
[06:51:17] [pool-6-thread-1/INFO]: Floodgate player who is logged in as .DynamicNeo00 00000000-0000-0000-0009-01fdf50f9c4c joined
[06:51:17] [Geyser Fabric connection thread-6-2/INFO]: Floodgate player logged in as .DynamicNeo00 disconnected
[06:51:17] [localSession-7-1/INFO]: DynamicNeo00 has disconnected from the Java server because of Network configuration task not supported: spell_engine:config
[06:51:17] [Server thread/INFO]: com.mojang.authlib.GameProfile@157e1f9a[id=00000000-0000-0000-0009-01fdf50f9c4c,name=.DynamicNeo00,properties={}] lost connection: Network configuration task not supported: spell_engine:config
[06:51:17] [Server thread/WARN]: handleDisconnection() called twice
[06:51:17] [Server thread/WARN]: handleDisconnection() called twice

**Comment by Izreaper** [comment]
Having the same issue! I am using Neoforge + Sinytra

**Comment by kaleb1496** [comment]
Has there been a fix for this issue? I am running into it as well!

**Comment by Tenta-dev** [comment]
Same here

I have a debug message :

fabric_networking_api_v1: Class version 65 required is higher than the class version supported by the current version of Mixin (JAVA_17 supports class version 61)


If that can help

**Comment by ZsoltMolnarrr** [comment]
I am afraid this issue is caused by Sinytra Connector incorrectly implementing network config stage handler registrations.
I'll have to investigate.

**Comment by b3loved** [comment]
My friend is having the same issue, but we don't have a Forge server, it's running on Fabric. The error code is exactly the same, what would be the issue then?

**Comment by ZsoltMolnarrr** [comment]
This is a confirmed issue of Forgified Fabric API (a component of Sinytra Connector).
I am unable to take any actions, since my usage of the original Fabric API is correctly coded.

**Comment by ZsoltMolnarrr** [comment]
Awaiting fix from Forgified Fabric API.
https://github.com/Sinytra/ForgifiedFabricAPI/pull/171

**Comment by ZsoltMolnarrr** [comment]
Solved by FFAPI update.

RPG Series via Sinytra Connector is now fully playable.

**Comment by Blu8901** [comment]
The issue is still happening for me, I don't know if I'm just dumb but I've been trying to fix it for weeks now. I'm using only fabric and getting the same error

"Network configuration task not supported: spell_engine:config" 

"[11:13:57] [User Authenticator #1/INFO]: UUID of player Blu890 is bf537a49-8b50-4a47-97bc-44048c2ca0cc
[11:13:57] [Server thread/INFO]: com.mojang.authlib.GameProfile@43e00ff6[id=bf537a49-8b50-4a47-97bc-44048c2ca0cc,name=Blu890,properties={textures=[Property[name=textures, value=ewogICJ0aW1lc3RhbXAiIDogMTc0MjkxNTYzNjcxOSwKICAicHJvZmlsZUlkIiA6ICJiZjUzN2E0OThiNTA0YTQ3OTdiYzQ0MDQ4YzJjYTBjYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJCbHU4OTAiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTAyZWYxNTE2NWEyYWRhZjE3NzNlODQwOWY1MzcwZTMyNmM1ODY0MjQ4NzA5ODRhMmVlNzFiMDMxYmU4OWQ0ZSIKICAgIH0sCiAgICAiQ0FQRSIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjM0MGMwZTAzZGQyNGExMWIxNWE4YjMzYzJhN2U5ZTMyYWJiMjA1MWIyNDgxZDBiYTdkZWZkNjM1Y2E3YTkzMyIKICAgIH0KICB9Cn0=, signature=gvTffzlPhQIejr+YXcp33iowEDJtlnOVkFmxfXc8oo2R17+EFC0RTndX+D/omSGljdwg7PYdEdoDq3PrhSqQLygUFLVvBHfrQTM1HeCYtZYSihd8l6w6QZIGzZqVk1dyEIsnmLldbXqNNlZk47DarQE3wm9kJKxQmDaAkPMX30FpuCYTlxvDu0JVUvThzUxZ9RMIKyTj7gSv2x24hiyLzGc9SPMshj2w2eml+DjVoM+Y9d6aGppukni2/81rzsbiaPRDygOY9GxJJS7N2KTnPNScgyvuwbhYCDj6HAkBTJsFXvRYhQi6uWUpWP26YDa19E0yslhKc9NhZjlpumPqSFQfCFwN5g5M5aYdRQKZE5RMjaYKrDUd4W/P4Pm4vqNPLj2Ru71/pjlyLN2124SvnlrKJSaPhcp446NghMKB9iXL25lfIhIVE2223rTEmqvZd5Ehho0ZbrTc19eLZhF7bhZxcPxOVOXU4lWkffGT1qzL3tuvHqb6cEySymOvz648ufhyvgzvDYE+JwTui410TO9pX7qEXtEtD97RoEft2IzXWN1XP2j4N3Cdl8cWJh5w1dEdPvylJllVwfQvIa6dpNE9HS8mk2ysQcqbtB6Z5ojkqJ0sUkdZ9jwZ8+kVIMGXOd/8llg3P8TC6uJpZjNI70vVT4lz9rIbNnQMDjh1cR8=]]}] lost connection: Network configuration task not supported: spell_engine:config
[11:13:57] [Server thread/WARN]: handleDisconnection() called twice
[11:13:57] [Server thread/WARN]: handleDisconnection() called twice"

Hopefully I'm just dumb and have been missing something but please help lol

Thanks
